version: "3.7"

services:
  app:
    image: "yilmazchef/cagri:latest"
    depends_on:
      db:
        condition: service_healthy
    restart: "unless-stopped"
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "cagri-app-disk:/app/data"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cagridb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_SQL_INIT_MODE=always
    networks:
      - codesapiens

  db:
    image: "postgres:latest"
    restart: "no"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cagridb" ]
    volumes:
      - "cagri-db-disk:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cagridb
    networks:
      - codesapiens

  dba:
    image: "dpage/pgadmin4:latest"
    restart: "on-failure"
    ports:
      - "5433:80"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@mail.be
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    networks:
      - codesapiens

networks:
  codesapiens:
    driver: bridge

volumes:
  cagri-app-disk:
    driver: local
  cagri-db-disk:
    driver: local

